CSPACE_URL = 'http://your_server:your_port/cspace-services/'
CSPACE_USER = 'username@collectionspace.org'
CSPACE_PASS = 'password'
CS_OBJECT_FILE = 'collectionspace_objects.pickle'
OAI_URL = 'http://example.org/oai/'
